name: Render

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.SERVICE_ID }}
